# Generated by Django 4.1.4 on 2023-01-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='latextext',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
