# Generated by Django 4.1.4 on 2023-01-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latex', '0003_text_finaltext_alter_text_latextext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='latextext',
        ),
    ]
